name: 🧪 Document

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: sebastienrousseau/pipelines/.github/workflows/docs.yml@v0.0.1
    with:
      type: rust
      deploy: true
      working-directory: .
