name: 🧪 Document

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs:
    name: Build Rust Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/rust-toolchain-cache
        with:
          toolchain: nightly
      - name: Build docs
        env:
          RUSTDOCFLAGS: --cfg docsrs
        run: cargo +nightly doc --all-features --no-deps
