name: 🌙 Nightly Maintenance

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  nightly-ci:
    uses: sebastienrousseau/pipelines/.github/workflows/rust-ci.yml@47ed7767be5273aef0bbc60c6f6c16aba5fb6f59 # v0.0.2
    with:
      rust-version: nightly
      run-clippy: true
      run-fmt: true
      run-audit: true
      run-coverage: false
