name: 🌙 Nightly Maintenance

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-ci:
    uses: sebastienrousseau/pipelines/.github/workflows/rust-ci.yml@v0.0.1
    with:
      rust-version: nightly
      run-clippy: true
      run-fmt: true
      run-audit: true
      run-coverage: false
