name: 🧪 Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: sebastienrousseau/pipelines/.github/workflows/release.yml@cf0413f34ee0f24fe52a32f39d26eca513f65713 # v0.0.1
    with:
      language: rust
      dry-run: false
    secrets:
      CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN || secrets.CARGO_API_TOKEN }}
