name: 🔍 Semver Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/semver.yml"
  workflow_dispatch:

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: http-handle
